// @flow

export default {
  ESC_POS_PRINTER_ACKNOWLEDGE_FAILED_OPERATION: 'ESC_POS_PRINTER_ACKNOWLEDGE_FAILED_OPERATION',

  ESC_POS_PRINTER_PRINT_DOCUMENT: 'ESC_POS_PRINTER_PRINT_DOCUMENT',
  ESC_POS_PRINTER_PRINT_DOCUMENT_SUCCEEDED: 'ESC_POS_PRINTER_PRINT_DOCUMENT_SUCCEEDED',
  ESC_POS_PRINTER_PRINT_DOCUMENT_FAILED: 'ESC_POS_PRINTER_PRINT_DOCUMENT_FAILED',
  ESC_POS_PRINTER_PRINT_DOCUMENT_IN_PROGRESS: 'ESC_POS_PRINTER_PRINT_DOCUMENT_IN_PROGRESS',
  ESC_POS_PRINTER_ACKNOWLEDGE_PRINT_DOCUMENT_OPERATION: 'ESC_POS_PRINTER_ACKNOWLEDGE_PRINT_DOCUMENT_OPERATION',
};
